### ISSUE TITLE
Window does not have statusBarStyle setter

### ISSUE THREAD

**Issue by yissachar** [ahome-it/ahome-titanium#11]
As per the [Titanium docs](http://docs.appcelerator.com/titanium/3.0/#!/api/Titanium.UI.Window-property-statusBarStyle), Window should have a `statusBarStyle` setter that controls the style of iOS status bar.

**Comment by eemi2010** [comment]
Indeed. We will add this. Thx.

**Comment by eemi2010** [comment]
Fixed with https://github.com/ahome-it/ahome-titanium/commit/c49735563e97fa033b02f514ad8e93e482642ad5
