### ISSUE TITLE
Latest commit breaks build

### ISSUE THREAD

**Issue by yissachar** [ahome-it/ahome-titanium#12]
Many of the Ui.create\* calls are broken currently, since the method signatures have changed.

I would fix this but I'm not sure how you would prefer it to be fixed. It seems there are two options:
- force all create\* calls to pass in null if they don't care about the params e.g. `UI.create2DMatrix(null, null)`
- add convenience methods that take no parameters and just forward the call with null e.g. 

```
static native JavaScriptObject create2DMatrix() {
    return create2DMatrix(null, null);
}
```

**Comment by eemi2010** [comment]
Indeed the last commit had lots of compile  error. We are currently adding support for Alloy
Sorry for breaking your build. We will fix this by the end of the week end.
.

**Comment by eemi2010** [comment]
You can see the Alloy support in action here : https://www.youtube.com/watch?v=2Uisx_Bp9l8.
How do you like it ;)

**Comment by yissachar** [comment]
That looks awesome :)

Being able to separate styling out and having instant live reload (no need to wait for compile!) seems like a huge win. I'm looking forward to trying it out.
