### ISSUE TITLE
Maven repo not kept up to date

### ISSUE THREAD

**Issue by yissachar** [ahome-it/ahome-titanium#14]
When searching for a Maven repo for Titanium4J we found https://oss.sonatype.org/content/repositories/snapshots/com/ahome-it/. However, it seems that it is not kept up to date and has a very old version of Titanium4J. This means we cannot use Maven for managing Titanium4J dependency and instead must manually download the JAR from the Ahome website, or build ourselves from Github sources, neither of which is ideal.

**Comment by eemi2010** [comment]
Agreed. We have been lazy updating the maven snapshot repository. We will fix this starting with today :)

**Comment by yissachar** [comment]
Great :)

**Comment by eemi2010** [comment]
OK. Latest Snapshot 4.1.0 is up. Enjoy :)

**Comment by yissachar** [comment]
Excellent! Really appreciate this.
