### ISSUE TITLE
New direct app.js generation broken

### ISSUE THREAD

**Issue by yissachar** [ahome-it/ahome-titanium#16]
The new generation method changed in ec1ea02060356106ed0174d6f7ac1c730b734cd5 does not seem to work correctly. It results in the error:

> ReferenceError: Can't find variable: exports

I was able to manually fix it by deleting `exports.` from the first line, and adding `start();` on the last line of `app.js`.

**Comment by eemi2010** [comment]
Fixed with https://github.com/ahome-it/ahome-titanium/commit/02c3f9a271f41ef0e950f82d7e2d95605b4e70c7

**Comment by eemi2010** [comment]
Please have a look an let us know if that works for you.

**Comment by yissachar** [comment]
That fixed the issue :+1:

**Comment by eemi2010** [comment]
Perfect. Closing this for now :)
