### ISSUE TITLE
Migrating an existing GWT app

### ISSUE THREAD

**Issue by aliakhtar** [ahome-it/ahome-titanium#2]
Hi there,

I have an existing GWT app which heavily uses UiBinder, CSS, and other GWT widgets.

What would be the steps needed for migrating this app to Titanium?

I'm guessing that all native GWT widgets would have to be replaced by Titanium widgets. What else might be needed? Will the rest of the app work mostly as is (i.e with uiBinder views)?

Also, will a web version of the app be available, or will it only be usable as mobile apps?

**Comment by eemi2010** [comment]
If the existing GWT is a web based mobile app then the easiest way would be to  create a hybrid app. Using titanium4j as a native shell to add native functionalities. We will have a blog post about that soon.

If you wish to have a 100% native app then  there is no way around a rewrite. 
Without knowing you app in details I cant tell if all the rest will work as it is.

If with a web version you mean a desktop app. Then the answer is no. Our tools make it easy to share code between desktop and mobile but you still need to write the desktop version yourself.

Hope that helps :)

**Comment by aliakhtar** [comment]
Hey,

Thanks for the reply.

My biggest concern is that I'm using a lot of UiBinder files for each view in the app. If I simply switch the  widgets in the uiBinder files from GWT widgets to Titanium4J widgets, will the app be mostly exportable?

I have a lot of CSS styling being done as well. Can most css styles be exported to Titanium?

Appreciate the help.

**Comment by eemi2010** [comment]
Hey there,

No they wont. You UIBinder files are GWT widget so they wont work inside Titanium4j. Actually anything DOM releated wont work inside Titanium4j unless you are using the webview. 

It looks like an hybrid app would be the best way  for you to go.

**Comment by aliakhtar** [comment]
I see. With a hybrid app, will it just be a webview? I'm currently using
Phonegap, is there any advantage to using Titanium over that if its going
to be a hybrid?

Thanks.

**Comment by eemi2010** [comment]
We found  building hybrid apps with titanium way better than Phonegap.
With Titanium you get everything in one place. Specially native UI components. With PhoneGap you need extra plugins, which break with each release.

Nothing against phonegap(we do maintain a GWT API for it too) but we just find the development experience way better with Titanium than Phonegap.
