### ISSUE TITLE
ListView class design is confusing and error prone

### ISSUE THREAD

**Issue by yissachar** [ahome-it/ahome-titanium#26]
[ListView](https://github.com/ahome-it/ahome-titanium/blob/master/ahome-titanium/src/main/java/com/ait/toolkit/titanium/mobile/client/ui/ListView.java) maintains an internal list of `sections` that is separate from the Titanium managed `sections`. This is confusing and error prone. It is very easy to enter a state where the internal `sections` are not synced with Titanium `sections` which will cause bugs.

For instance, the following:

```
List<ListSection> sections = new ArrayList<ListSection>();
ListView listView = new ListView(sections);
listView.addSection(new ListSection());
```

will result in an error, because the `ListSection...` constructor never initialized `this.sections`.

Another example:

```
listView.addSection(new ListSection());
listView.setSections(new ArrayList<ListSection>()
listView.addSection(new ListSection());
```

We would expect only one ListSection but it actually results in two sections for the ListView since `setSections` does not update the internal `sections`. In fact, if you use `addSections`, there is no way to remove a section from the internal `sections`.

While it is possible to fix these issues on a one-by-one basis, I think the better fix would be to address the root cause and remove the internal `sections` and associated methods.

As far as I understand, the motivation for adding an internal `sections` is to have control over rendering and prevent rendering at each `setSections` call. However, it seems this can be accomplished just as well through the Titanium `appendSections` method which adds multiple ListSections to the ListView at once. Being that this is the case, the internal `sections` do not add any value, and only serve to make the class more complicated to reason about, and cause errors.

**Comment by eemi2010** [comment]
True. The initial goal why we added the section field does not fit anymore. I will remove the field soon. Thx.

**Comment by eemi2010** [comment]
Fixed.
