### ISSUE TITLE
Blob methods not recognized

### ISSUE THREAD

**Issue by yissachar** [ahome-it/ahome-titanium#32]
I am able to use a Blob and add it to an image, but when I try to call Blob methods they are not found.

For instance the following works fine:

```
Blob blob = listView.toImage();
ImageView imageView = new ImageView();
imageView.setImage(blob);
add(imageView);
```

But if I try:

```
Blob thumb = blob.imageAsThumbnail(25);
```

I get the error:

> Uncaught TypeError: Object #<Object> has no method 'imageAsThumbnail`

The same applies to methods `getImageFileDimensions` and `imageAsCropped`.

According to the [docs](http://docs.appcelerator.com/platform/latest/#!/api/Titanium.Blob) all these methods should exist.

**Comment by eemi2010** [comment]
How is the toImage() implemented ? We dont support that yet.

**Comment by yissachar** [comment]
I am just using the default View [toImage()](https://github.com/ahome-it/ahome-titanium/blob/master/ahome-titanium/src/main/java/com/ait/toolkit/titanium/mobile/client/ui/View.java#L1444).

**Comment by eemi2010** [comment]
It looks like that method is returning null. we should actually check that the returned js object is not nulll before wrapping it. If it s null then we should return null

**Comment by yissachar** [comment]
I have a non-null Blob object. Actually, printing it out gives me an object that doesn't seem to match the Titanium docs at all. It has the following properties:

```
mimeType
height
width
media
x
y
cropRect
```

I'm not really sure what's going on.

**Comment by eemi2010** [comment]
ok will have to investigate this ....

**Comment by yissachar** [comment]
Here is a simple program that reproduces the issue:

```
Window window = new Window();
window.setBackgroundColor(Color.ALICEBLUE);
window.setLayout(View.ViewLayout.VERTICAL);

View greenBox = new View();
greenBox.setBackgroundColor(Color.GREEN);
greenBox.setTop(50);
greenBox.setLeft(50);
greenBox.setHeight(50);
greenBox.setWidth(50);
window.add(greenBox);

Blob blob = greenBox.toImage();

ImageView boxAsImage = new ImageView();
boxAsImage.setImage(blob);
boxAsImage.setTop(50);
boxAsImage.setLeft(50);
window.add(boxAsImage);

ImageView thumbImage = new ImageView();
Blob cropped = blob.imageAsCropped(10, 10, 10, 10); // <-- fails here
thumbImage.setImage(cropped);
thumbImage.setTop(50);
thumbImage.setLeft(50);
window.add(thumbImage);

window.open();
```

**Comment by eemi2010** [comment]
Thx for the report. Will have a look asap

**Comment by eemi2010** [comment]
What s not working for you. The code above seems to work for me.

![ti4jpic](https://cloud.githubusercontent.com/assets/2421746/7990780/939b52b2-0af3-11e5-9021-d9a173a4511d.png)

**Comment by yissachar** [comment]
Interesting... it seems to work fine on iOS , although the image seems to need explicit height and width set otherwise it expands to the screen edges as you see.

If you add these two lines:

```
boxAsImage.setHeight(50);
boxAsImage.setWidth(50);
```

You should see this:
![screen shot 2015-06-04 at 2 36 18 pm](https://cloud.githubusercontent.com/assets/2190867/7991578/2a3335dc-0ac7-11e5-9664-c72dac674061.png)

Which is the correct result.

However, when I try on Android I get the exception:

> Type: TypeError
> Message: Object #<Object\> has no method 'imageAsCropped'
> File: eval at <anonymous\> : api/PlatformRequire.js
> Line: 60
> At:   com_ait_toolkit_titanium_mobile_client_blob_Blob_$imageAsCropped__Lcom_ait_toolkit_titanium_mobile_client_blob_Blob_2IIIILcom_ait_toolkit_titanium_mobile_client_blob_Blob_2

Even though the docs say that the method is supported both on Android and iOS.

I wonder if this is an upstream Titanium issue, since the Titanium4J code seems to be just simple calls into the underlying methods and it works correctly on iOS.

**Comment by eemi2010** [comment]
That  looks like one of those titanium mobile quirks. Have u tried that on a real android device ?

**Comment by yissachar** [comment]
Yes, it is the same on the device. 

I've just managed to reproduce this using pure Titanium, so I'm going to go file a bug with Appcelerator, and link it back here. Thanks for the help!

**Comment by eemi2010** [comment]
You welcome. Keep up the good work.

**Comment by eemi2010** [comment]
Please share the link to the titanium bug.

**Comment by yissachar** [comment]
Here's the current link: https://jira.appcelerator.org/browse/TC-5553

That might change if they upgrade it to a TiMob bug.

**Comment by yissachar** [comment]
Updated link: https://jira.appcelerator.org/browse/TIMOB-18982
