### ISSUE TITLE
Nested network request causes error on iOS

### ISSUE THREAD

**Issue by yissachar** [ahome-it/ahome-titanium#35]
The following code which makes a request to fetch google.com and upon completion makes a new request to fetch google.com a second time:

```
Window window = new Window();
window.setBackgroundColor(Color.ALICEBLUE);
window.addOpenHandler(new UIEventHandler() {
    @Override
    public void onEvent(UIEvent event) {
        RequestBuilder requestBuilder = new RequestBuilder(RequestBuilder.GET, "http://google.com");
        try {
            requestBuilder.sendRequest("", new RequestCallback() {
                @Override
                public void onResponseReceived(Request request, Response response) {
                    RequestBuilder requestBuilder = new RequestBuilder(RequestBuilder.GET, "http://google.com");
                    try {
                        requestBuilder.sendRequest("", new RequestCallback() {
                            @Override
                            public void onResponseReceived(Request request, Response response) {
                                Titanium.alert("Fetched");
                            }

                            @Override
                            public void onError(Request request, Throwable exception) {
                                Titanium.alert(exception.getMessage());
                            }
                        });
                    } catch (RequestException e) {
                        Titanium.alert(e.getMessage());
                    }
                }

                @Override
                public void onError(Request request, Throwable exception) {
                    Titanium.alert(exception.getMessage());
                }
            });
        } catch (RequestException e) {
            Titanium.alert(e.getMessage());
        }
    }
});
window.open();
```

gives me the error: 

> undefined is not an object (evaluating '$wnd.setTimeout')";

on iOS. Android makes the requests without any error.

I tested a pure Titanium version in JavaScript with nested HTTPClient requests but it worked fine, so it seems that this bug is in Titanium4J only.

**Comment by yissachar** [comment]
It just occurred to me that there is a Titanium4J `HttpClient`, but changing the sample code to use that results in the same error.

**Comment by eemi2010** [comment]
Strange. Will have a look.

**Comment by yissachar** [comment]
Any update on this? So far we've been able to avoid nested network calls, but we now have a scenario where we need to make a nested network call and this issue is blocking us.

**Comment by eemi2010** [comment]
Sorry I havent had the time to look into this since I havent heard from you.
I thought you fixed the issue. Will have a look asap.

Is this happening on the simulator  ?

**Comment by yissachar** [comment]
No worries - I haven't really looked into this either since we have been able to avoid the issue until now.

It is happening on the simulator.

**Comment by eemi2010** [comment]
Should be fixed now. There was a wrong reference to the $wnd object inside com.google.gwt.core.client.impl.Impl
Please pull from master (or patch the class locally) and let me know if it works for u

![screenshot_03_09_15_02_48](https://cloud.githubusercontent.com/assets/2421746/9648256/c2863b66-51e6-11e5-9cff-81908e2b6a96.png)

**Comment by yissachar** [comment]
Confirmed as fixed. Thanks!
