### ISSUE TITLE
Integrator and Platforms examples do not exist

### ISSUE THREAD

**Issue by yissachar** [ahome-it/ahome-titanium#5]
The [examples page](http://titanium4j.ahome-it.com/examples/) lists Integrator and Platforms examples, however unlike the other examples on the page, clicking "Get Example Source" does not get the source, but rather redirects you to http://www.ahome-it.com/contact/.

These examples also do not exist in the GitHub repo.

**Comment by eemi2010** [comment]
This examples are only for our support members for now. As a small startup we are trying to find the right balance between between giving everything out for free and adding paid support. 

We hope you guyz understand :)

**Comment by yissachar** [comment]
No worries, I understand. I think it should be made more clear that this is the case though.

**Comment by eemi2010** [comment]
Indeed. We are working on adding new content on the website. 
Should be out soon.
