### ISSUE TITLE
Checking if Platform is iOS

### ISSUE THREAD

**Issue by yissachar** [ahome-it/ahome-titanium#6]
The Platform class provides several methods for determining what version and device of iOS we are running on:

```
isIPad
isIPhone
isIOs3_2Plus
isIOS4Plus
```

However, there is no plain `isIOS` method. Additionally, the  `isIOs3_2Plus`, `isIOS4Plus` do not seem to work correctly from what I can tell (running an iPhone 4s simulator).

Currently the iOS check can be accomplished by checking for both iPhone and iPad:

`Platform.get().isIPhone() || Platform.get().isIPad()`

Or alternatively, by checking the platform name:

`Platform.get().getName().equalsIgnoreCase(Platform.PLATFORM_IPHONE_OS)`

However, I think it would be best if Platform encapsulated this in the form of an isIOS method.

**Comment by eemi2010** [comment]
Thx. Indeed this looks like something useful we should add. Will do.
