### ISSUE TITLE
ActionBar does not have hide method

### ISSUE THREAD

**Issue by yissachar** [ahome-it/ahome-titanium#8]
According to the [Titanium docs](http://docs.appcelerator.com/titanium/3.0/#!/api/Titanium.Android.ActionBar) ActionBar should have a hide method that hides the ActionBar, however this does not exist in Titanium4J.

**Comment by eemi2010** [comment]
Thx. We will fix this asap

**Comment by eemi2010** [comment]
Fixed with https://github.com/ahome-it/ahome-titanium/commit/81e10f5be672f31a43b3e973d7464184a0c04383
